version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      npm run dev -- --host 0.0.0.0
    working_dir: /app
    ports:
      - 5173:5173
      - 5174:5174
    volumes:
      - ./:/app
    tty: true
